[package]
name = "firekeeper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive", "env"] }
futures = "0.3"
globset = "0.4"
grep = "0.4.1"
html2md = "0.2"
ignore = "0.4"
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
toml = "0.9.11"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
